name: Deploy to server
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Raspberry Pi
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "Desktop/VOCO-bot"
          target: "/home/${{ secrets.USERNAME }}/Desktop/VOCO-bot"
      - name: Run server script
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd /home/${{ secrets.USERNAME }}/Desktop/VOCO-bot && ./server.sh"
